export const list = [
  {
    id: "629",
    name: "Baby Alpaca-Wool Diamond Stitch Crew",
    description:
      "<p>Soft, textured, tactile. We love that our alpaca crewneck sweater has an oversized silhouette with a light feel. It has a diamond stitch pattern with an incredibly soft texture for ultimate easy styling and comfort. Alpaca wool is long lasting and resistant to pilling, and doesn't have the scratchiness of some other wools.</p>",
    price: 254.41,
    discountedPrice: 216.11,
    colors: ["#FF0000", "#000000", "#0000FF"],
    images: [
      "https://images.quince.com/HqgYbDsh8IPoTIdDt6lCa/606d34bdae4faa71895b1aa63df98be4/W-BRAC-12_0025.jpg",
      "https://images.quince.com/placeholder_image_path/629_img2.jpg",
    ],
    features: [
      "Limited edition",
      "Comfortable fit",
      "Eco-friendly",
      "High-quality materials",
    ],
    size: ["L", "XL", "XS", "M", "XXL"],
    rating: 3.6,
    category: "Mens_Sweaters",
    internal_product_name: "Women's Alpaca Diamond Stitch Crew",
    style_number: "W-SWT-25",
    gender: "female",
    details:
      "<ul><li>Knit with baby alpaca wool, extrafine merino wool, and nylon</li><li>12 gauge</li><li>Lightweight, insulating, and soft to the touch</li><li>Given the nature of the alpaca yarns used, it is normal to see some shedding and pilling</li><li>Alpaca wool sourced from Peru and knitted in Dongguan, China</li></ul>",
    seo_title: "Baby Alpaca-Wool Diamond Stitch Crew",
    subclass_name: "Long Sleeve",
    class_name: "Crewneck",
    subdepartment_name: "Alpaca",
    department_name: "Sweaters",
    division_name: "Womens",
  },
  {
    id: "630",
    name: "Baby Alpaca-Wool Diamond Stitch Crew 2",
    description:
      "<p>Soft, textured, tactile. We love that our alpaca crewneck sweater has an oversized silhouette with a light feel. It has a diamond stitch pattern with an incredibly soft texture for ultimate easy styling and comfort. Alpaca wool is long lasting and resistant to pilling, and doesn't have the scratchiness of some other wools.</p>",
    price: 254.41,
    discountedPrice: 216.11,
    colors: ["#FF0000", "#000000", "#0000FF"],
    images: [
      "https://images.quince.com/HqgYbDsh8IPoTIdDt6lCa/606d34bdae4faa71895b1aa63df98be4/W-BRAC-12_0025.jpg",
      "https://images.quince.com/placeholder_image_path/629_img2.jpg",
    ],
    features: [
      "Limited edition",
      "Comfortable fit",
      "Eco-friendly",
      "High-quality materials",
    ],
    size: ["L", "XL", "XS", "M", "XXL"],
    rating: 3.6,
    category: "Mens_Sweaters",
    internal_product_name: "Women's Alpaca Diamond Stitch Crew",
    style_number: "W-SWT-25",
    gender: "female",
    details:
      "<ul><li>Knit with baby alpaca wool, extrafine merino wool, and nylon</li><li>12 gauge</li><li>Lightweight, insulating, and soft to the touch</li><li>Given the nature of the alpaca yarns used, it is normal to see some shedding and pilling</li><li>Alpaca wool sourced from Peru and knitted in Dongguan, China</li></ul>",
    seo_title: "Baby Alpaca-Wool Diamond Stitch Crew",
    subclass_name: "Long Sleeve",
    class_name: "Crewneck",
    subdepartment_name: "Alpaca",
    department_name: "Sweaters",
    division_name: "Mens",
  },
  {
    id: "631",
    name: "Baby Alpaca-Wool Diamond Stitch Crew 2",
    description:
      "<p>Soft, textured, tactile. We love that our alpaca crewneck sweater has an oversized silhouette with a light feel. It has a diamond stitch pattern with an incredibly soft texture for ultimate easy styling and comfort. Alpaca wool is long lasting and resistant to pilling, and doesn't have the scratchiness of some other wools.</p>",
    price: 254.41,
    discountedPrice: 216.11,
    colors: ["#FF0000", "#000000", "#0000FF"],
    images: [
      "https://images.quince.com/HqgYbDsh8IPoTIdDt6lCa/606d34bdae4faa71895b1aa63df98be4/W-BRAC-12_0025.jpg",
      "https://images.quince.com/placeholder_image_path/629_img2.jpg",
    ],
    features: [
      "Limited edition",
      "Comfortable fit",
      "Eco-friendly",
      "High-quality materials",
    ],
    size: ["L", "XL", "XS", "M", "XXL"],
    rating: 3.6,
    category: "Mens_Sweaters",
    internal_product_name: "Women's Alpaca Diamond Stitch Crew",
    style_number: "W-SWT-25",
    gender: "female",
    details:
      "<ul><li>Knit with baby alpaca wool, extrafine merino wool, and nylon</li><li>12 gauge</li><li>Lightweight, insulating, and soft to the touch</li><li>Given the nature of the alpaca yarns used, it is normal to see some shedding and pilling</li><li>Alpaca wool sourced from Peru and knitted in Dongguan, China</li></ul>",
    seo_title: "Baby Alpaca-Wool Diamond Stitch Crew",
    subclass_name: "Long Sleeve",
    class_name: "Crewneck",
    subdepartment_name: "Alpaca",
    department_name: "Sweaters",
    division_name: "Womens",
  },
  {
    id: "632",
    name: "Baby Alpaca-Wool Diamond Stitch Crew 2",
    description:
      "<p>Soft, textured, tactile. We love that our alpaca crewneck sweater has an oversized silhouette with a light feel. It has a diamond stitch pattern with an incredibly soft texture for ultimate easy styling and comfort. Alpaca wool is long lasting and resistant to pilling, and doesn't have the scratchiness of some other wools.</p>",
    price: 254.41,
    discountedPrice: 216.11,
    colors: ["#FF0000", "#000000", "#0000FF"],
    images: [
      "https://images.quince.com/HqgYbDsh8IPoTIdDt6lCa/606d34bdae4faa71895b1aa63df98be4/W-BRAC-12_0025.jpg",
      "https://images.quince.com/placeholder_image_path/629_img2.jpg",
    ],
    features: [
      "Limited edition",
      "Comfortable fit",
      "Eco-friendly",
      "High-quality materials",
    ],
    size: ["L", "XL", "XS", "M", "XXL"],
    rating: 3.6,
    category: "Mens_Sweaters",
    internal_product_name: "Women's Alpaca Diamond Stitch Crew",
    style_number: "W-SWT-25",
    gender: "female",
    details:
      "<ul><li>Knit with baby alpaca wool, extrafine merino wool, and nylon</li><li>12 gauge</li><li>Lightweight, insulating, and soft to the touch</li><li>Given the nature of the alpaca yarns used, it is normal to see some shedding and pilling</li><li>Alpaca wool sourced from Peru and knitted in Dongguan, China</li></ul>",
    seo_title: "Baby Alpaca-Wool Diamond Stitch Crew",
    subclass_name: "Long Sleeve",
    class_name: "Crewneck",
    subdepartment_name: "Alpaca",
    department_name: "Sweaters",
    division_name: "Mens",
  },
];
